name: Go Test

on: [push, pull_request]

jobs:

  helloci-build:
    name: Test with go
    runs-on: [ubuntu-latest]
    environment:
      name: secrets
    steps:
      - name: Tidy
        run: |
          echo ${{secrets.USER_NAME}}
